import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'

const backendRoot = path.resolve(__dirname, '../..')
const read = (relativePath: string) => fs.readFileSync(path.join(backendRoot, relativePath), 'utf8')
const mzapp = read('src/modules/mzapp.ts')
const cleaningApp = read('src/modules/cleaning_app.ts')
const migration = read('scripts/migrations/20260806_property_feedback_history_access_control.sql')
const historyListStart = mzapp.indexOf("router.get('/property-feedbacks'")
const historyListEnd = mzapp.indexOf("router.post('/property-feedbacks'", historyListStart)
assert(historyListStart >= 0 && historyListEnd > historyListStart, 'property feedback history route must exist')
const historyListRoute = mzapp.slice(historyListStart, historyListEnd)

assert.match(historyListRoute, /FROM properties[\s\S]*WHERE \(\$1::text IS NOT NULL AND id::text = \$1\)/)
assert.doesNotMatch(historyListRoute, /feedback_source_task_required/)
assert.match(mzapp, /created_by_user_id text/)
assert.match(mzapp, /updated_by_user_id text/)
assert.match(mzapp, /deleted_by_user_id text/)
assert.match(mzapp, /hasOnlyPropertyFeedbackContentFields/)
assert.match(mzapp, /feedback_content_fields_only/)
assert.match(mzapp, /kind === 'maintenance' && !Object\.keys\(parsed\.data\)\.length/)
assert.match(mzapp, /feedback_content_fields_required/)
assert.match(mzapp, /new Set\(\['area', 'category', 'detail', 'note', 'media_urls', 'repair_photo_urls'\]\)/)
assert.match(mzapp, /loadPropertyFeedbackRow\('maintenance', id, client, true\)/)
assert.match(mzapp, /forbidden_property_feedback_completion/)
assert.match(mzapp, /maintenance_completion_edit_requires_workflow/)
assert.match(mzapp, /maintenance_completion_photo_required/)
assert.match(mzapp, /completion_photo_urls: normalizeUrlArray\(row\.completion_photo_urls\)/)
assert.match(mzapp, /s === 'closed'\) return 'resolved'/)
assert.match(mzapp, /'completed','done','ready','closed'/)
assert.match(mzapp, /canAccessPropertyFeedbackRow/)
assert.match(mzapp, /hasRole\(user, 'offline_manager'\)/)
assert.match(mzapp, /deleted_at = now\(\)/)
assert.match(mzapp, /deleted_by_user_id = \$2/)
assert.match(mzapp, /created_by_user_id \|\| ''/)
assert.match(mzapp, /const id = require\('uuid'\)\.v4\(\)/)
assert.match(mzapp, /source_id = \$3/)
assert.doesNotMatch(mzapp, /DELETE FROM \$\{table\} WHERE id = \$1 RETURNING id/)
assert.match(cleaningApp, /JOIN properties p ON p\.id::text = m\.property_id::text/)
assert.match(cleaningApp, /m\.deleted_at IS NULL/)
assert.match(cleaningApp, /canViewMzappPropertyFeedback\(user, feedbackMediaRow, userId\)/)
assert.doesNotMatch(cleaningApp.slice(cleaningApp.indexOf("'/media/image'"), cleaningApp.indexOf("'/upload'", cleaningApp.indexOf("'/media/image'"))), /requireAnyPerm/)
assert.match(migration, /created_by_user_id text/)
assert.match(migration, /deleted_at timestamptz/)
assert.match(migration, /deleted_by_user_id text/)

const patchRouteStart = mzapp.indexOf("router.patch('/property-feedbacks/:kind/:id'")
const maintenancePatchStart = mzapp.indexOf("if (kind === 'maintenance')", patchRouteStart)
const deepCleaningPatchStart = mzapp.indexOf("if (kind === 'deep_cleaning')", maintenancePatchStart)
assert(patchRouteStart >= 0 && maintenancePatchStart > patchRouteStart && deepCleaningPatchStart > maintenancePatchStart)
const maintenancePatchRoute = mzapp.slice(maintenancePatchStart, deepCleaningPatchStart)
const emptyMaintenancePayloadGuard = mzapp.indexOf("feedback_content_fields_required", patchRouteStart)
assert(emptyMaintenancePayloadGuard > patchRouteStart && emptyMaintenancePayloadGuard < maintenancePatchStart, 'empty maintenance PATCH must be rejected before any transaction or audit-field update')
assert.match(maintenancePatchRoute, /updated_by_user_id = \$9/)
assert.match(
  maintenancePatchRoute,
  /nextCompletionEvidenceMedia = Array\.from\(new Set\(\[\s*\.\.\.normalizeUrlArray\(row\.completion_photo_urls\),\s*\.\.\.nextRepairMedia,/,
  'pending-review photo requirement must accept separately stored authoritative completion photos after editable supplements are removed',
)
assert.match(maintenancePatchRoute, /workflowStatus === 'pending_review' && !nextCompletionEvidenceMedia\.length/)
assert.doesNotMatch(maintenancePatchRoute, /\bstatus\s*=/, 'generic maintenance content editing must not change workflow status')
assert.doesNotMatch(maintenancePatchRoute, /\breview_status\s*=/, 'generic maintenance content editing must not change review status')
assert.doesNotMatch(maintenancePatchRoute, /\bcompleted_at\s*=/, 'generic maintenance content editing must not change completion timestamp')

console.log('property feedback access contract: PASS')
